CREATE DATABASE IF NOT EXISTS todo_project;
USE todo_project;

CREATE TABLE IF NOT EXISTS users(
  ID INT AUTO_INCREMENT NOT NULL,
  username VARCHAR(30) NOT NULL,
  email VARCHAR(254) NOT NULL,
  password VARCHAR(64) NOT NULL,
  created TIMESTAMP NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS tasks(
  ID INT AUTO_INCREMENT NOT NULL,
  user_id INT NOT NULL,
  title VARCHAR(40) NOT NULL,
  done BOOLEAN DEFAULT 0,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  finished TIMESTAMP ,
  deleted TIMESTAMP,
  PRIMARY KEY(ID),
  FOREIGN KEY (user_id) REFERENCES users(ID)
);

DESCRIBE users
DESCRIBE tasks